title: Albers.gdb.zip Geodatabase Archive
description: An archival copy and simplified version of the USDA Farm Service Agency dd17 county boundaries dataset.
author: R. Kyle Bocinsky
url: "https://sustainable-fsa.github.io/fsa-lfp-counties/"  # Your GitHub Pages URL
baseurl: "/fsa-lfp-counties"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
