# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main

name: update
run-name: Update the FSA LFP Counties archive

permissions: write-all

defaults:
  run:
    shell: bash -l {0}

jobs:
  update-fsa-lfp-counties:
    name: update-fsa-lfp-counties
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: mt-climate-office/actions/setup-geospatial@v1

      - name: run
        run: |
          Rscript fsa-lfp-counties.R

      - name: commit
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit --allow-empty -m 'Update Archive'
          git pull --rebase
          git push
